### ISSUE TITLE
Use "exhib" instead of "rapist"

### ISSUE THREAD

**Issue by LukyVj** [bullgit/bullias#2]

**Comment by Haroenv** [comment]
Good point, that one's over the top, but I don't think `exhib` is that much better. It's still a crime ...

**Comment by Haroenv** [comment]
maybe `flash` would make sense

**Comment by LukyVj** [comment]
Yes, but still less "shocking" and brutal IMO. Nah? I mean, the rapist one was clearly too much..

**Comment by LukyVj** [comment]
Just in case, Fixed in 4d70f9f6
